#!/usr/bin/env python3

"""
Direct executable script for the Pulp Fiction Generator CLI.
"""

import sys
import os
from pulp_fiction_generator.__main__ import app

if __name__ == "__main__":
    sys.exit(app()) 