"""
Custom templates for agent prompts and responses.
"""

from .system_templates import DEFAULT_SYSTEM_TEMPLATE, CREATIVE_SYSTEM_TEMPLATE, ANALYTICAL_SYSTEM_TEMPLATE
from .prompt_templates import DEFAULT_PROMPT_TEMPLATE, CREATIVE_PROMPT_TEMPLATE, ANALYTICAL_PROMPT_TEMPLATE
from .response_templates import DEFAULT_RESPONSE_TEMPLATE, CREATIVE_RESPONSE_TEMPLATE, ANALYTICAL_RESPONSE_TEMPLATE

__all__ = [
    # System templates
    'DEFAULT_SYSTEM_TEMPLATE',
    'CREATIVE_SYSTEM_TEMPLATE',
    'ANALYTICAL_SYSTEM_TEMPLATE',
    
    # Prompt templates
    'DEFAULT_PROMPT_TEMPLATE',
    'CREATIVE_PROMPT_TEMPLATE',
    'ANALYTICAL_PROMPT_TEMPLATE',
    
    # Response templates
    'DEFAULT_RESPONSE_TEMPLATE',
    'CREATIVE_RESPONSE_TEMPLATE',
    'ANALYTICAL_RESPONSE_TEMPLATE'
]